id: dataseeding_script
learningObjectives: 
- Populating DB using a dataseeding script 
hints:
- Oh, OK! [Here's]( https://trywilco.notion.site/Data-seeding-f5f1a3260e8c47bd8f8cd3fcadf6b6dc) something that might help.
- Try to **find the code in the backend that creates an item in the DB** and **see how it creates the item** on the DB.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: You know I value your time, so when I had to pick between having you seed the database with users, items and comments manually, and **using a script** - I went for the script.
        delay: 800
      - text: The script file, `seeds.sh`, is in the backend directory right now, waiting for you to :codeInstruction[implement it]. So go ahead, implement away! 
        delay: 1500
      - text: The script should connect directly to the database and seed it with :codeInstruction[**100 users, 100 products, and 100 comments.**]
        delay: 1000
      - text: "Oh, wait, there’s a note here with some details: you should run the script on the backend docker container, using `docker exec -it anythink-backend-${user.backend} bash`."
        delay: 2500
      - text: Once you’re done, :codeInstruction[open a PR].
        delay: 800
githubActions:
  backend:
    testFile: psql.sql
    cmd:
      - /bin/bash -c "DATABASE_URL=${databaseUrl} ./seeds.sh"
      - psql ${databaseUrl} -f ${testFile} -v ON_ERROR_STOP=1
    paramsFramework:     
      node:
        testFile: mongo.js
        cmd: 
          - /bin/bash -c "MONGODB_URI=${databaseUrl} ./seeds.sh"
          - mongo ${testFile}

      
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: That was fast! I'll review the changes right away.
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Wonderful! Looks like there are some records in your local DB. Now you can :codeInstruction[**merge the PR**] and get ready for your next assignment.
                delay: 1300
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: Nice! Looks like there are some records in your local DB. Now you can **merge the PR** and come **back to Snack** once you’re ready.
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
              - text: Umm, something is off. **Make sure all [checks](${githubWorkflowRunUrl}) pass** and only then try and merge the PR. 
                delay: 1700
              - text: Don't hesitate to **ask for my help** by admitting that you're :input[stuck]{text="I'm stuck!"} and I'm your only hope 👼
                delay: 2500
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: Umm, something is off. **Make sure all [checks](${githubWorkflowRunUrl}) pass** and **only then try and merge** the PR (or you can always ask for my help on Snack).
        github_pr_merged:
          do:
          - actionId: finish_step

solution:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
      paramsFramework:
        node:
          messages:
            - text: Alright, what we need to do now is add what's called a `seed` script that basically "seeds" the database with some initial data.
            - text: "In our case, we want to fill our database with 100 different entries (sometimes referred to as \"records\") for each one of the three entities: users, items and comments."
            - text: If you'll look under the `backend/scripts` directory you'll find an empty file called `seeds.js`, which we should fill with code to seed the database.
            - text: "Now, in order to do that we first need to establish a database connection. We can look how that is done in `backend/app.js` and copy it:"
            - text: |
                ```
                  const mongoose = require("mongoose");
                  const connection = process.env.MONGODB_URI;
                  mongoose.connect(connection);
                ```
            - text: "Next, it would probably be easiest to use the existing Mongoose models (`User`, `Item` and `Comment`) that are already used in the existing app code to insert 100 entries of each into the database. We should first import them:"
            - text: |
                ```
                const User = mongoose.model("User");
                const Item = mongoose.model("Item");
                const Comment = mongoose.model("Comment");
                ```
            - text: "Now, if we stop to think about the next step: in what order should we add these 3 entities? `items` \"belong\" to `users`, and `comments` \"belong\" to `items`. Therefore, it makes sense to add them in the following order:"
            - text: "- Add 100 `users`"
            - text: "- Add 100 `items` that are associated to these existing `users` (could be one item for each user or 100 items for just one user)"
            - text: "- Add 100 `comments` that are associated to these existing `items` (again, in any way we see fit as long they each are connected to an item)"
            - text: "Note that we could theoretically add them in any order we want, but then we'd have to run over them again to associate the items to users and comments to items. With this suggested order we can do this in a single run."
            - text: "Now let's start inserting the seed data to the database. Since we'll be using some async functions, we should put the code within an async function. Within it we could construct a 'for' loop, iterating over it 100 times, like so:"
            - text: |
                ```
                  async function seedDatabase() {
                    for (let i = 0; i < 100; i++) {
                      const user = {};
                      user.username = `user${i}`;
                      user.email = `user${i}@gmail.com`;
                      const options = { upsert: true, new: true };
                      const createdUser = await User.findOneAndUpdate(user, {}, options);
                      const item = {
                        slug: `slug${i}`,
                        title: `title ${i}`,
                        description: `description ${i}`,
                        seller: createdUser,
                      };
                      const createdItem = await Item.findOneAndUpdate(item, {}, options);
                      if (!createdItem?.comments?.length) {
                        let commentIds = [];
                        for (let j = 0; j < 100; j++) {
                          const comment = new Comment({
                            body: `body ${j}`,
                            seller: createdUser,
                            item: createdItem,
                          });
                          await comment.save();
                          commentIds.push(comment._id);
                        }
                        createdItem.comments = commentIds;
                        await createdItem.save();
                      }
                    }
                  }
                ```
        rails:
          messages:
            - text:
        python:
          messages:
            - text:
