id: dataseeding_add_item
learningObjectives: 
- Manually adding an item to the DB 
hints:
- Oh, OK! Maybe you should try to **find the page that lets you add new items.**
- Still stuck, ah? Try to find **which api route adds an item to the DB, and which piece of code in the frontend calls it**
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: In Anythink, almost all our features revolve around data. The database contains registered users, items, comments, and much more.  
        delay: 800
      - text: You can't test your code when your database is emptier than the office fridge after the unfortunate ferret accident.
        delay: 1000
      - text: So go ahead, :codeInstruction[**add a single item to the DB**], then get to :codeInstruction[**its page in the system**] to continue.
        delay: 1200
      - text: This is not a coding task. Just use the system like a regular Anythink user.
        delay: 1000
trigger:
  type: local_page_load
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        params:
          text: "${path}"
          regex: ^/item/
          flags: i
      then:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: OK! Good! You have an item in the system, and that’s fantastic.
              delay: 800
            - text: But why would you put ${Lodash.startCase(Lodash.dropRight(path.slice(6).split("-")).join("-"))} as your choice?
              delay: 1300
            - text: Nevermind that, as Anythink's motto says - "Never ask questions you don't want to know the answers to." Moving on! ✨
              delay: 1700
        - actionId: finish_step

solution:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: Ok let's solve this part together. Basically what we want to do here is add a new `item` to our marketplace using the web UI, like any user of ours would.
          - text: Start by accessing the frontend server in the browser, then click on `Sign up` at the top right (if you aren't logged in yet) and complete the form.
          - text: You should now be logged in and able to see a `New Item` button at the top right menu. Click it.
          - text: Add a dummy item - give it a title and description (you can leave image and tags fields blank), then click the `Publish Item` button.
          - text: You've just added an item to the marketplace! That should be it for this step.
